# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='av_long',
            field=models.TextField(default='AV: '),
        ),
        migrations.AddField(
            model_name='character',
            name='av_short',
            field=models.CharField(default='AV: ', max_length=50),
        ),
    ]
