# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20171027_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='av_long',
            field=models.TextField(blank=True),
        ),
    ]
