# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0003_auto_20171027_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='campaign_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.CharacterIcon'),
        ),
    ]
