# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20171028_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charactericon',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
