# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0004_auto_20171028_2023'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_dttm', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(default='There we were...', max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Heal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Combat')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Combat')),
            ],
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_val', models.IntegerField(default=0)),
                ('effect_txt', models.CharField(max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Combat')),
            ],
        ),
        migrations.CreateModel(
            name='StatusEffectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bandaged', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Combat')),
            ],
        ),
        migrations.AddField(
            model_name='statuseffect',
            name='effect_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.StatusEffectType'),
        ),
        migrations.AddField(
            model_name='combat',
            name='game_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Day'),
        ),
    ]
