# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='name',
            field=models.CharField(default='Goblins', max_length=200),
            preserve_default=False,
        ),
    ]
