# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-29 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_combat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
