# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-30 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('tracker', '0004_auto_20171029_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='group',
        ),
        migrations.RemoveField(
            model_name='round',
            name='combat',
        ),
        migrations.RemoveField(
            model_name='combat',
            name='game_day',
        ),
        migrations.AddField(
            model_name='combat',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
